name: 'Spring Boot Bake'
description: 'Generate docker-bake.hcl and Dockerfile for "docker/bake-action" to build Spring Boot Docker Image'

branding:
  color: 'green'
  icon: 'power'

inputs:
  base-image:
    description: 'The base image to use for the Docker image'
    required: false
    default: 'eclipse-temurin:11-jre-alpine'

outputs:
  bake-file:
    description: 'The path to the generated docker-bake.hcl file'
    value: "${{ github.action_path }}/spring-boot-bake.hcl"
  dockerfile:
    description: 'The path to the generated Dockerfile'
    value: "${{ github.action_path }}/Dockerfile"

runs:
  using: 'composite'
  steps:
    - name: 'Spring Boot Bake'
      shell: bash
      run: |
        echo "Baking the Spring Boot Docker Image"
        echo "SPRING_BOOT_BAKE_PATH=${{ github.action_path }}" >> $GITHUB_ENV
        echo "SPRING_BOOT_BAKE_BASE_IMAGE=${{ inputs.base-image }}" >> $GITHUB_ENV
