name: 'Spring Boot Bake'
description: 'Generate docker-bake.hcl and Dockerfile for "docker/bake-action" to build Spring Boot Docker Image'

branding:
  color: 'green'
  icon: 'power'

inputs:
  base-image:
    description: 'The base image to use for the Docker image'
    required: false
    default: 'eclipse-temurin:11-jre-alpine'
  template:
    description: 'Set (default) will use the default Dockerfile template, or specify a custom template. Available templates: default, plain'
    default: default

outputs:
  bake-file:
    description: 'The path to the generated docker-bake.hcl file'
    value: ${{ steps.meta.outputs.bake-file }}
  dockerfile:
    description: 'The path to the generated Dockerfile'
    value: ${{ steps.meta.outputs.dockerfile }}

runs:
  using: 'composite'
  steps:
    - name: 'Spring Boot Bake'
      shell: bash
      id: meta
      run: ${{ github.action_path }}/spring-boot-bake.sh "${{ inputs.base-image }}" "${{ inputs.template }}"
