ARG JAVA_DISTRIBUTION=eclipse-temurin
ARG JAVA_VERSION=11
ARG JAVA_VARIANT=jre
ARG JAVA_PLATFORM=alpine
ARG JAVA_IMAGE=${JAVA_DISTRIBUTION}:${JAVA_VERSION}-${JAVA_VARIANT}-${JAVA_PLATFORM}

FROM ${JAVA_IMAGE}
